### ISSUE TITLE
 Error: Currenty there is no connection to the server. 

### ISSUE THREAD

**Issue by hardikpoojara** [johnnymast/mysql_websocket_chat#3]
Hello Developer,

Thank you so much for creating awesome script for chat using websocket. Unfortunately i'm getting one error  **Error: Currenty there is no connection to the server.** . I can not understand how to resolve that. i did the same server settings as you mentioned.

Please note i'm using mysqli connection as my **PHP Version 7.1.7** and 

![image](https://user-images.githubusercontent.com/16718829/29576591-084b06aa-8786-11e7-9fa3-49bc65329425.png)

Please advise me where i'm going wrong..

Thanks !
Hardik

**Comment by johnnymast** [comment]
Hello Hardik,

Sorry for my late response. Change the follow line to your ip address and then browse to it in your browser. Tell me if that did the trick.

https://github.com/johnnymast/mysql_websocket_chat/blob/9704eea288228fded089bd4df221267de9f83abe/includes/config.php#L15

**Comment by johnnymast** [comment]
Also dont forget to start the server by running php ./server.php

**Comment by SLAppsDev** [comment]
@johnnymast getting the same error, so if I'm running on my localhost, do I need to change this line? 
`define('CHAT_SERVER_HOST',   'localhost'); `

**Comment by johnnymast** [comment]
Thats correct change it to your local ip and try again. Also notice that ports lower then 1024 are often blocked because they require privileges. 

If your local ip is 192.168.2.1 then set that as ip and browse to that ip in your browser. If that doesn’t work you can also try 0.0.00. Are you running Windows as well? The standard script runs fine for me on Mac.

**Comment by SLAppsDev** [comment]
@johnnymast actually im running it on Mac, this is the configuration.php that I have 

```php
date_default_timezone_set('EUROPE/AMSTERDAM');

define ('DATABASE_HOST', '127.0.0.1');
define ('DATABASE_USERNAME', 'root');
define ('DATABASE_PASSWORD', '');
define ('DATABASE_DB', 'socket_chat');
define ('ENABLE_DATABASE', true);

define('CHAT_SERVER_HOST', 'localhost');
define('CHAT_SERVER_PORT', '8080');
```

I'm getting this message when I execute the server.php script 

> Server running at localhost:8080


![screen shot 2017-11-08 at 11 12 06](https://user-images.githubusercontent.com/32457138/32562982-ac98ec0a-c475-11e7-9390-98b92f71eb54.png)

**Comment by johnnymast** [comment]
Did you try changing the ip to your local ip ex 192.168.1.2 and then browse to it? Also test it running trough mamp. 

Im gonna test it now but im on windows atm but then again i will run it

**Comment by johnnymast** [comment]
Did you try changing the ip to your local ip ex 192.168.1.2 and then browse to it? Also test it running trough mamp. 

Im gonna test it now but im on windows atm but then again i will run it

**Comment by johnnymast** [comment]
Did you try changing the ip to your local ip ex 192.168.1.2 and then browse to it? Also test it running trough mamp. 

Im gonna test it now but im on windows atm but then again i will run it

**Comment by SLAppsDev** [comment]
@johnnymast  yeah I did change it to my local ip but same error, does it really matter if its mamp or xamp??

**Comment by SLAppsDev** [comment]
@johnnymast  yeah I did change it to my local ip but same error, does it really matter if its mamp or xamp??

**Comment by johnnymast** [comment]
Well i actually dont know im gonna record a live setup now .. i will sent it to youtube today maybe you missed something.

**Comment by johnnymast** [comment]
@hardikpoojara dont forget to make he index.php folder your document root for the chat. I see that its not loading /css/style.css for you because on your setup its /mysql_websocket_chat/css/style.css but the html points to /css/style.css the same for the javascript needed to connect to the socketserver.

**Comment by johnnymast** [comment]
@hardikpoojara @SLAppsDev here is a video for you guys.

https://www.youtube.com/watch?v=oscZAV_5n70

**Comment by SLAppsDev** [comment]
@johnnymast Great video, the missing step was the same as you, the path in the server, but I wonder why would we need to setup the server to the project directory in order to work?, what I mean is that if mamp in your computer is pointing to desktop, why would you need to change it to point to Desktop/chat?

**Comment by johnnymast** [comment]
Mamp is not required but easier to setup. You can use php -s as well.

![image](https://user-images.githubusercontent.com/121194/32571593-442c4ba0-c4c8-11e7-87f4-1a84850ae3dd.png)

**Comment by johnnymast** [comment]
@hardikpoojara @SLAppsDev can i close this issue now?

**Comment by johnnymast** [comment]
Problem solved.
