### ISSUE TITLE
1.3 SSL Error handshake error

### ISSUE THREAD

**Issue by johnnymast** [johnnymast/mysql_websocket_chat#4]
Hi,

I am using your websocket script in one of my application, when doing this on http this works like charm

But when trying to do this on ssl, getting "handshake error"

Using Ubuntu 16.04 with apache 2.4.18

can you please suggest on how to enable the script to use with ssl

Thanks

**Comment by kkarayat** [comment]
When trying to run this script over http, it works without any issue, screenshot attached
![without_https_1](https://user-images.githubusercontent.com/13733255/34159900-e831938e-e4f0-11e7-8d27-182362a4f457.png)
![withouthttps](https://user-images.githubusercontent.com/13733255/34159902-e89c093a-e4f0-11e7-92b7-aef95cc105b5.png)

Here is the screenshot of the server instance running

![server_instance](https://user-images.githubusercontent.com/13733255/34159946-1959e722-e4f1-11e7-8363-e082cbb16962.png)

Now below are the screenshot when I am trying to execute the script over https, I have generated self-signed certificates for apache

![with_https](https://user-images.githubusercontent.com/13733255/34160090-93065024-e4f1-11e7-831a-6001bc4c497b.png)

Now since I have to use this in one of the website I am working which runs overs https, so it is mandatory for me to you https.

I have used wss instead of ws in websocket.js file

**Comment by johnnymast** [comment]
In screenshot 4 it shows it is the web browser that has no ssl capabilty. I suggest to look up howto run local php with a self signed ssl certificate. Or you can take a litle bit of your time and learn laravel valet that allows you to run ssl sites on your local computer.

https://laravel.com/docs/5.5/valet

I did install this yesterday in 20 minutes. After you installed if lookup the section about 

```
valet secure laravel
```

**Comment by kkarayat** [comment]
As mentioned above I have generated self signed certificate and when trying to run other sites over https it works without any issue, its just the issue with sockets which does not work over https, do you think some other settings apart for module ws_tunnel needs to be done in apache configuration

**Comment by johnnymast** [comment]
The issue is now closes as @kkarayat noted that it now works over ssl.
